// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package v1

// PostPasteTextBody defines parameters for PostPaste.
type PostPasteTextBody = string

// PostPasteTextRequestBody defines body for PostPaste for text/plain ContentType.
type PostPasteTextRequestBody = PostPasteTextBody
